"""Add methodology and project_type to projects

Revision ID: 1ad2ecab212f
Revises: 
Create Date: 2025-09-17 17:35:14.151446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad2ecab212f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('methodology', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('project_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_type')
    op.drop_column('projects', 'methodology')
    # ### end Alembic commands ###
